# Preprocessing config
preprocess:
  input: data/raw/data.csv
  output: 
    train : data/processed/train.csv
    test: data/processed/test.csv
    val: data/processed/val.csv

# Training config
train:
  train_data: data/processed/train.csv
  val_data :  data/processed/val.csv 
  test_data : data/processed/test.csv
  model: models/model.pkl