# Preprocessing config
preprocess:
  input: data/raw/data.csv
  train_output: data/processed/train.csv
  val_output: data/processed/val.csv
  test_output: data/processed/test.csv

# Training config
train:
  train_data: data/processed/train.csv
  val_data :  data/processed/val.csv 
  test_data : data/processed/test.csv
  model: models/model.pkl